// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-JKGyWnAdmEKeuFwYisgn7N11w3K2nvk',
    appId: '1:704240145068:web:2651a52835d46071f0c509',
    messagingSenderId: '704240145068',
    projectId: 'chat-app-5c30c',
    authDomain: 'chat-app-5c30c.firebaseapp.com',
    storageBucket: 'chat-app-5c30c.firebasestorage.app',
    measurementId: 'G-RSCF7M8N01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQA9Vvk0s6ka47QDb1wBzaIsHBzR2ft4U',
    appId: '1:704240145068:android:4d65e86e757cd3b2f0c509',
    messagingSenderId: '704240145068',
    projectId: 'chat-app-5c30c',
    storageBucket: 'chat-app-5c30c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwM881zUgYV6Ed_9vJW2lCq5oWcel7jtI',
    appId: '1:704240145068:ios:6b84aa705ae4e7eef0c509',
    messagingSenderId: '704240145068',
    projectId: 'chat-app-5c30c',
    storageBucket: 'chat-app-5c30c.firebasestorage.app',
    iosBundleId: 'com.example.simplechatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwM881zUgYV6Ed_9vJW2lCq5oWcel7jtI',
    appId: '1:704240145068:ios:6b84aa705ae4e7eef0c509',
    messagingSenderId: '704240145068',
    projectId: 'chat-app-5c30c',
    storageBucket: 'chat-app-5c30c.firebasestorage.app',
    iosBundleId: 'com.example.simplechatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-JKGyWnAdmEKeuFwYisgn7N11w3K2nvk',
    appId: '1:704240145068:web:2a95851ff0c49d5bf0c509',
    messagingSenderId: '704240145068',
    projectId: 'chat-app-5c30c',
    authDomain: 'chat-app-5c30c.firebaseapp.com',
    storageBucket: 'chat-app-5c30c.firebasestorage.app',
    measurementId: 'G-2EG5WW4LY2',
  );
}
